# Generated by Django 2.2.12 on 2020-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_request_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='metadata_locked',
            field=models.BooleanField(default=False),
        ),
    ]
