# Generated by Django 2.2.15 on 2020-10-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0003_track_metadata_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-showtime']},
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.CharField(
                choices=[
                    ('tblc', '{user.name} bought Take Back Love City for the RSPCA.'),
                    (
                        'charity-2016',
                        (
                            '{user.name} donated to the Very Scary Scenario charity'
                            ' streams for Special Effect in 2016.'
                        ),
                    ),
                    (
                        'charity-2017',
                        (
                            '{user.name} donated to the Very Scary Scenario charity'
                            ' streams and Neko Desu All-Nighter for Cancer Research UK'
                            ' in 2017.'
                        ),
                    ),
                    (
                        'charity-2018',
                        (
                            '{user.name} donated to the Very Scary Scenario charity'
                            ' streams for Cancer Research UK in 2018.'
                        ),
                    ),
                    (
                        'charity-2019',
                        (
                            '{user.name} donated to the Very Scary Scenario charity'
                            ' streams for Samaritans in 2019.'
                        ),
                    ),
                    (
                        'charity-2020',
                        (
                            '{user.name} donated to the Very Scary Scenario charity'
                            ' streams in 2020.'
                        ),
                    ),
                ],
                max_length=12,
            ),
        ),
    ]
