# Generated by Django 2.2.17 on 2021-05-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20201024_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vote',
            name='kind',
            field=models.CharField(
                blank=True,
                choices=[
                    ('email', 'email'),
                    ('discord', 'discord'),
                    ('text', 'text'),
                    ('tweet', 'tweet'),
                    ('person', 'in person'),
                    ('phone', 'on the phone'),
                ],
                max_length=10,
            ),
        ),
    ]
