# Generated by Django 3.2.14 on 2022-08-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0006_auto_20220423_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id3_artist',
            field=models.CharField(max_length=5000),
        ),
    ]
