# Generated by Django 3.2.17 on 2023-02-09 21:14

from django.db import migrations, models
import django_resized.forms
import nkdsu.apps.vote.models


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0013_alter_vote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_abuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_patron',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=['middle', 'center'],
                force_format='PNG',
                help_text='will be resized to 500x500 and converted to png, so provide that if you can',
                keep_meta=False,
                quality=-1,
                scale=None,
                size=[500, 500],
                upload_to=nkdsu.apps.vote.models.avatar_upload_path,
            ),
        ),
    ]
