# Generated by Django 3.2.17 on 2023-02-09 22:10

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def give_users_profiles(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('vote', 'Profile')

    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)


def do_nothing(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vote', '0014_auto_20230209_2114'),
    ]

    operations = [migrations.RunPython(give_users_profiles, do_nothing)]
