# Generated by Django 3.2.17 on 2023-02-10 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def remove_unsuccessful_trivia_requests(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    Request = apps.get_model('vote', 'Request')
    Request.objects.filter(successful=False).delete()


def do_nothing(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    pass


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0015_give_users_profiles'),
    ]

    operations = [
        migrations.RunPython(remove_unsuccessful_trivia_requests, do_nothing),
        migrations.RemoveField(
            model_name='request',
            name='successful',
        ),
        migrations.AddField(
            model_name='request',
            name='submitted_by',
            field=models.ForeignKey(
                blank=True,
                help_text='the person who submitted this request',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='submitted_requests',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='request',
            name='claimant',
            field=models.ForeignKey(
                blank=True,
                help_text='the elf who is taking care of this request',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='claims',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='request',
            name='filled_by',
            field=models.ForeignKey(
                blank=True,
                help_text='the elf who fulfilled this request',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='request',
            name='track',
            field=models.ForeignKey(
                blank=True,
                help_text='the track that this request is about, if this is a request for a correction',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='vote.track',
            ),
        ),
    ]
