runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: pip install -r requirements.txt
      shell: bash

    - run: npm install
      shell: bash

    - run: python ./manage.py migrate --settings=nkdsu.settings_testing
      shell: bash

    - run: python ./manage.py collectstatic --no-input --settings=nkdsu.settings_testing
      shell: bash
