runs:
  using: "composite"
  steps:
    - run: git submodule update --init --recursive
      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: pip install poetry
      shell: bash

    - run: poetry install
      shell: bash

    - run: npm install
      shell: bash

    - run: poetry run ./manage.py migrate --settings=nkdsu.settings_testing
      shell: bash

    - run: poetry run ./manage.py collectstatic --no-input --settings=nkdsu.settings_testing
      shell: bash
