default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args: [--pretty, --show-error-context]
        language: system
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.33.0
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@7.32.0
        -   eslint-config-standard@16.0.3
        -   eslint-plugin-import@2.25.2
        -   eslint-plugin-node@11.1.0
        -   eslint-plugin-promise@5.1.0
        -   less@4.1.2
        -   uglify-js@3.14.2
        -   yuglify@2.0.0
        files: nkdsu/static/js/
