[tool.black]
skip-string-normalization = true
color = true

[tool.mypy]
files =  "."
ignore_missing_imports = true
plugins = [
  "mypy_django_plugin.main"
]
warn_unused_ignores = true

[tool.django-stubs]
django_settings_module = "nkdsu.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "nkdsu.settings_testing"
python_files = "*.py"
addopts = "--doctest-modules --doctest-glob=*.rst --numprocesses=auto --dist=worksteal --pyargs"
